.PHONY: clean
clean:
	-rm -f *.aux
	-rm -f *.log
	-rm -f *.toc
	-rm -f *.bbl
	-rm -f *.blg
	-rm -f *.out
	-rm -f *.gz
	-rm -f *.brf
	-rm -f *.xml
	-rm -f main-blx.bib

.PHONY: eradicate
eradicate: clean
	-rm -f *.pdf
	-rm -f *.ps
	-rm -f *.dvi
